name: Python Code Quality and Lint

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.4.0